blank_issues_enabled: true
contact_links:
  - name: タスク追加
    about: タスク忘れていると思われるとき or タスクを依頼したいとき
    url: https://github.com/noko1024/human-life/issues/new?template=TaskNew.md&projects=noko1024/projects/2&labels=NEW&assignees=noko1024
